// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEipC868t6fYPh7kd5nhas1XlpqwQ08Vk',
    appId: '1:636518506767:web:4f966675fafc9f43801e7a',
    messagingSenderId: '636518506767',
    projectId: 'flutter-project-basic',
    authDomain: 'flutter-project-basic.firebaseapp.com',
    storageBucket: 'flutter-project-basic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx2BDzr8ibnWY9DRODE86Q-3Ql-kIQ6H8',
    appId: '1:636518506767:android:2faea9bae7ea4792801e7a',
    messagingSenderId: '636518506767',
    projectId: 'flutter-project-basic',
    storageBucket: 'flutter-project-basic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACTg5mpoaKGqjZsxk7r1T3oO_0DNiaZhw',
    appId: '1:636518506767:ios:b6df1f29f0d3f509801e7a',
    messagingSenderId: '636518506767',
    projectId: 'flutter-project-basic',
    storageBucket: 'flutter-project-basic.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACTg5mpoaKGqjZsxk7r1T3oO_0DNiaZhw',
    appId: '1:636518506767:ios:568e5ca375d4e81a801e7a',
    messagingSenderId: '636518506767',
    projectId: 'flutter-project-basic',
    storageBucket: 'flutter-project-basic.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
